version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #   - ./volumes/db/data:/var/lib/postgresql/data:Z
    #   - postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    networks:
      - server

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

    networks:
      - server

  pg-to-redis-listener:
    build: ./pg_to_redis_listener
    volumes:
      - ./pg-to-redis-listener:/app
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_DB=${POSTGRES_DB:-yourdbname}
      - POSTGRES_USER=${POSTGRES_USER:-youruser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=${REDIS_HOST:-redis}
    depends_on:
      - db
      - redis
    networks:
      - server

  backend:
    build: ./backend
    command: uvicorn server:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=yourdbname
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_PORT=5432
      - SQLALCHEMY_URL=postgresql://youruser:yourpassword@db:5432/yourdbname
      - NEXTAUTH_SECRET=yoursecret
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
      - redis
    networks:
      - server
    # develop:
    #   watch:
    #     - path: ./backend/requirements.txt
    #       action: rebuild
    #     - path: ./backend
    #       target: /app/backend
    # action: sync

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=yournodeenv
      - NEXT_PUBLIC_ENDPOINT_URL=http://localhost:8000
      - NEXT_PUBLIC_SUPABASE_URL=yoursupabaseurl
      - NEXT_PUBLIC_SUPABASE_KEY=yoursupabasekey
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=yourclerkpublishablekey
      - CLERK_SECRET_KEY=yourclerksecretkey
      - NEXT_PUBLIC_AMPLITUDE_API_KEY=youramplitudeapikey
      - NEXT_PUBLIC_SELF_HOSTED=yourselfhosted
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=yoursecret
      - NEXT_PUBLIC_ORG_NAME=yourorgname
      - NEXT_PUBLIC_ORG_SLUG=yourorgslug
      - NEXT_PUBLIC_AUTH_GOOGLE_CLIENT_ID=yourgoogleclientid
      - NEXT_PUBLIC_AUTH_GOOGLE_CLIENT_SECRET=yourgoogleclientsecret
      - NEXT_PUBLIC_AUTH_GITHUB_CLIENT_ID=yourgithubclientid
      - NEXT_PUBLIC_AUTH_GITHUB_CLIENT_SECRET=yourgithubclientsecret
    command: npm run start
    depends_on:
      - backend
    networks:
      - server
    x-watch:
      - path: ./path_to_your_nextjs_app
        action: sync+restart

networks:
  server:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
