version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - server

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

    networks:
      - server

  pg-to-redis-listener:
    build:
      context: ./pg_to_redis_listener
      args:
        - POSTGRES_HOST=db
        - POSTGRES_DB=${POSTGRES_DB:-postgres}
        - POSTGRES_USER=${POSTGRES_USER:-youruser}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
        - POSTGRES_PORT=${POSTGRES_PORT:-5432}
        - REDIS_HOST=redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-youruser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - server
    restart: always

  backend:
    build:
      context: ./backend
      args:
        - POSTGRES_HOST=db
        - POSTGRES_DB=${POSTGRES_DB:-postgres}
        - POSTGRES_USER=${POSTGRES_USER:-youruser}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
        - POSTGRES_PORT=${POSTGRES_PORT:-5432}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-yoursecret}
        - NEXTAUTH_URL=http://localhost:3000
        - PORT=8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-youruser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yourpassword}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-yoursecret}
      - NEXTAUTH_URL=http://localhost:3000
      - PORT=8000
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - server
    restart: always
    develop:
      watch:
        - path: ./backend/requirements.txt
          action: rebuild
        - path: ./backend
          action: rebuild
          # action: sync

  frontend:
    build:
      context: ./frontend
      args:
        - NEXTAUTH_URL=http://localhost:3000
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-yoursecret}
        - NEXT_SERVER_ENDPOINT_URL=http://backend:8000/api
        - NEXT_PUBLIC_ENDPOINT_URL=http://localhost:8000/api
        - NEXT_PUBLIC_SELF_HOSTED=true
    # command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-yoursecret}
      - NEXT_SERVER_ENDPOINT_URL=http://backend:8000/api
      - NEXT_PUBLIC_ENDPOINT_URL=http://localhost:8000/api
      - NEXT_PUBLIC_SELF_HOSTED=true
    depends_on:
      backend:
        condition: service_started
      pg-to-redis-listener:
        condition: service_started
    networks:
      - server
    # restart: always
    develop:
      watch:
        - path: ./frontend
          action: rebuild
          # action: sync
        - path: ./frontend/package.json
          action: rebuild

networks:
  server:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
