"""add_on_delete_cascade_on_version_uuid

Revision ID: 97ad559a7d01
Revises: 73f8df3ae3ae
Create Date: 2024-01-05 17:01:04.311773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ad559a7d01'
down_revision: Union[str, None] = '73f8df3ae3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_log_session_uuid_fkey', 'chat_log', type_='foreignkey')
    op.drop_constraint('chat_log_user_message_uuid_fkey', 'chat_log', type_='foreignkey')
    op.create_foreign_key(None, 'chat_log', 'chat_message', ['user_message_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_log', 'chat_session', ['session_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('chat_message_session_uuid_fkey', 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'chat_session', ['session_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('function_model_version_function_model_uuid_fkey', 'function_model_version', type_='foreignkey')
    op.create_foreign_key(None, 'function_model_version', 'function_model', ['function_model_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('prompt_version_uuid_fkey', 'prompt', type_='foreignkey')
    op.create_foreign_key(None, 'prompt', 'function_model_version', ['version_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('run_log_version_uuid_fkey', 'run_log', type_='foreignkey')
    op.create_foreign_key(None, 'run_log', 'function_model_version', ['version_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    
    op.drop_constraint('users_organizations_organization_id_fkey', 'users_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'users_organizations', 'organization', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_organizations', type_='foreignkey')
    op.create_foreign_key('users_organizations_organization_id_fkey', 'users_organizations', 'organization', ['organization_id'], ['organization_id'])
    op.drop_constraint(None, 'run_log', type_='foreignkey')
    op.create_foreign_key('run_log_version_uuid_fkey', 'run_log', 'function_model_version', ['version_uuid'], ['uuid'])
    op.drop_constraint(None, 'prompt', type_='foreignkey')
    op.create_foreign_key('prompt_version_uuid_fkey', 'prompt', 'function_model_version', ['version_uuid'], ['uuid'])
    op.drop_constraint(None, 'function_model_version', type_='foreignkey')
    op.create_foreign_key('function_model_version_function_model_uuid_fkey', 'function_model_version', 'function_model', ['function_model_uuid'], ['uuid'])
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key('chat_message_session_uuid_fkey', 'chat_message', 'chat_session', ['session_uuid'], ['uuid'])
    op.drop_constraint(None, 'chat_log', type_='foreignkey')
    op.drop_constraint(None, 'chat_log', type_='foreignkey')
    op.create_foreign_key('chat_log_user_message_uuid_fkey', 'chat_log', 'chat_message', ['user_message_uuid'], ['uuid'])
    op.create_foreign_key('chat_log_session_uuid_fkey', 'chat_log', 'chat_session', ['session_uuid'], ['uuid'])
    # ### end Alembic commands ###
