"""add_function_model_version_created_by

Revision ID: dfcc59a1a1bd
Revises: abe2d78b38ba
Create Date: 2024-01-17 14:08:17.923577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcc59a1a1bd'
down_revision: Union[str, None] = 'abe2d78b38ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_model_version', sa.Column('created_by', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'function_model_version', 'user', ['created_by'], ['user_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('project', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_public')
    op.drop_constraint(None, 'function_model_version', type_='foreignkey')
    op.drop_column('function_model_version', 'created_by')
    # ### end Alembic commands ###
